#!/usr/bin/env python3

import numpy as np
import rospy
import state_representation as sr
from controllers import create_cartesian_controller, CONTROLLER_TYPE
from dynamical_systems import create_cartesian_ds, DYNAMICAL_SYSTEM_TYPE
from network_interfaces.control_type import ControlType
from network_interfaces.zmq.network import CommandMessage
from rospy_zmq_examples.robot_interface import RobotInterface


def control_loop(robot, freq):
    target_set = False
    command = CommandMessage()
    command.control_type = [ControlType.EFFORT.value]

    ds = create_cartesian_ds(DYNAMICAL_SYSTEM_TYPE.POINT_ATTRACTOR)
    ds.set_parameter_value("gain", [50., 50., 50., 10., 10., 10.], sr.ParameterType.DOUBLE_ARRAY)

    ctrl = create_cartesian_controller(CONTROLLER_TYPE.COMPLIANT_TWIST)
    ctrl.set_parameter_value("linear_principle_damping", 1., sr.ParameterType.DOUBLE)
    ctrl.set_parameter_value("linear_orthogonal_damping", 1., sr.ParameterType.DOUBLE)
    ctrl.set_parameter_value("angular_stiffness", .5, sr.ParameterType.DOUBLE)
    ctrl.set_parameter_value("angular_damping", .5, sr.ParameterType.DOUBLE)

    rate = rospy.Rate(freq)
    while not rospy.is_shutdown():
        state = robot.get_state()
        if not state:
            continue
        if not target_set:
            target = sr.CartesianPose(state.ee_state.get_name(), np.array([.3, .4, .5]), np.array([0., 1., 0., 0.]),
                                      state.ee_state.get_reference_frame())
            ds.set_parameter_value("attractor", target, sr.ParameterType.STATE, sr.StateType.CARTESIAN_POSE)
            target_set = True
        else:
            twist = sr.CartesianTwist(ds.evaluate(state.ee_state))
            twist.clamp(.25, .5)
            command_torques = sr.JointTorques(ctrl.compute_command(twist, state.ee_state, state.jacobian))
            command.joint_state = state.joint_state
            command.joint_state.set_torques(command_torques.get_torques())
            robot.send_command(command)
        rate.sleep()


if __name__ == '__main__':
    rospy.init_node("test", anonymous=True)

    robot_interface = RobotInterface("*:1601", "*:1602")
    control_loop(robot_interface, 500)
